#!/bin/bash

# Find our current path
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

linkit () {
	if (( $# == 1 )); then
		echo -n Installing $1 ...
		ln -s ${BASE_DIR}/$1 ~/.$1 2>/dev/null
		if (( $? == 0 )); then
			echo ok
		else
			echo  fail!
		fi
	elif (( $# > 1 )); then
		echo -n Installing $1 to $2 ...
		ln -s ${BASE_DIR}/$1 $2 2>/dev/null
		if (( $? == 0 )); then
			echo ok
		else
			echo  fail!
		fi
	fi
}

# git
linkit gitconfig

# vim
linkit vimrc
linkit vimrc ~/.config/nvim/init.vim
# and bootstrap dein
if [[ ! -d ~/.dein ]]; then
	curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
	chmod u+x installer.sh
	./installer.sh ~/.dein
	rm installer.sh
fi
# emacs
linkit emacs.d

# shells
linkit bashrc
linkit zshrc

# tmux
linkit tmux.conf
linkit tmuxline.conf


