#!/bin/bash

# Find our current path
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

linkit () {
	if (( $# == 1 )); then
		destpath=~/.$1
	elif (( $# > 1 )); then
		destpath=$2
	else
		return 1
	fi

	if [[ -h $destpath ]]; then
		echo $1 is already linked.
		return
	fi
	if [[ -e $destpath ]]; then
		echo $1 exists but is not a link. Please move it and rerun the script.
		return 1
	fi

	echo -n Installing $1 to $destpath ...
	ln -s ${BASE_DIR}/$1 $destpath 2>/dev/null
	if (( $? == 0 )); then
		echo ok
	else
		echo fail!
	fi
}

# git
linkit gitconfig

# vim
linkit vimrc
# emacs
linkit spacemacs

# shells
linkit profile
linkit bashrc

# wms
linkit Xresources
linkit urxvt
mkdir -p ~/.config
linkit i3 ~/.config/i3
linkit i3status.conf
